### PR TITLE
Update metadata

### PR DESCRIPTION
**Pull request by vipulgupta2048**
Strangely, the license used is LGPLv2+ but in licensecheck tests, I have found no trace of it. I might have missed it somewhere hence will keep it. Along with this, the test also showed presence of MIT license but that was in some copyright files 

`DrGeo/vm_arm/share/doc/squeak-vm/copyright: MIT/X11 (BSD like)`
`DrGeo/vm_64/share/doc/squeak-vm/copyright: MIT/X11 (BSD like)`

Hence, didn't put it there. Will be adding screenshots.

### CODE REVIEW

**Comment by quozl** [comment]
Activity doesn't work, so won't review.  See issues list.

**Comment by vipulgupta2048** [comment]
@quozl Umm... It worked in my system. I also got the screenshots, uploading them now. 
Screenfetch output below for system config
```
                  yyyyy- -yyyy      OS: Ubuntu 16.04 xenial
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 4.15.0-29-generic
           .++ .:/++++++/-.+sss/`      Uptime: 23h 24m
         .:++o:  /++++++++/:--:/-      Packages: 2454
        o:+o+:++.`..```.-/oo+++++/     Shell: fish
       .:+o:+o/.          `+sssoo+/    Resolution: 1920x1080
  .++/+:+oo+o:`             /sssooo.   DE: XFCE
 /+++//+:`oo+o               /::--:.   WM: Xfwm4
 \+/+o+++`o++o               ++////.   WM Theme: Numix
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Canta-dark-compact [GTK2]
       .+.o+oo:.          `oddhhhh+    Icon Theme: Canta
        \+.++o+o``-````.:ohdhhhhh+     Font: Noto Sans 12
         `:o+++ `ohhhhhhhhyo++os:      CPU: Intel Core i5-7200U CPU @ 3.1GHz
           .o:`.syhhhhhhh/.oo++o`      GPU: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
               /osyyyyyyo++ooo+++/     RAM: 2421MiB / 7876MiB

```

**Comment by quozl** [comment]
Reviewed to ecff226.

> It worked on my system

Interesting, thanks.  I guess we can close https://github.com/sugarlabs/DrGeo/issues/2 ... do you think this might be because your system has _squeak-vm_ installed?

**Comment by vipulgupta2048** [comment]
No, not to my knowledge.

**Comment by quozl** [comment]
Thanks.  I've tested on Ubuntu 18.04 using current head of _master_, and it works fine.

**Pull request merged**
